import { Inter } from "next/font/google";
import Footer from "./components/Footer";
import Header from "./components/Header";
import Signup from "./components/Signup";
import "./styles/main.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Unbeatable Loans",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
        <Signup />
      </body>
    </html>
  );
}
